import React from "react";
import { motion } from "motion/react";

const projects = [
  {
    title: "Video Delivery Quality & Cost Analytics Platform",
    period: "April 2026",
    description:
      "Analytics platform for video delivery quality, CDN cost governance, and edge capacity analysis. The system combines real YouTube metadata, synthetic CDN delivery logs, PostgreSQL, Python/SQL metric pipelines, A/B testing, bootstrap confidence intervals, Streamlit dashboards, and local LLM-assisted reporting with deterministic statistical diagnostics as the source of truth.",
    highlights: [
      "Analysed latency, start-up time, rebuffer ratio, cache hit rate, CDN cost, and edge utilisation",
      "Built treatment-control A/B testing with hypothesis testing and bootstrap confidence intervals",
      "Used local Ollama for grounded analytics summaries while keeping SQL/Python diagnostics as source of truth"
    ],
      stack: [
      "Python",
      "SQL",
      "PostgreSQL",
      "Streamlit",
      "pandas",
      "NumPy",
      "YouTube Data API",
      "Bash",
      "Ollama",
      "A/B Testing",
      "Bootstrap CI"
    ],
    link: "https://github.com/kenny1031/llm-video-delivery-analytics",
  },
  {
    title: "Airbnb Retrieval Ranking Engine",
    period: "April 2026",
    description:
      "Built a full-stack natural-language Airbnb search engine over 36K+ listings using FastAPI, PostgreSQL, and React + TypeScript.",
    highlights: [
      "Designed a two-stage retrieval and reranking pipeline using MiniLM embeddings for top-100 candidate retrieval and an XGBoost reranker over 28 engineered relevance features",
      "Trained the reranker from pseudo-labels generated by a rule-based teacher score, combining semantic similarity with structured signals such as price fit, review quality, room type, amenities, and location match",
      "Implemented query-intent parsing for preferences such as budget, wifi, family-friendliness, cancellation policy, and guest capacity in a hybrid ranking framework",
      "Added unit and integration tests for parsing, reranking, and API search flows to improve reliability and reproducibility",
    ],
    stack: ["FastAPI", "PostgreSQL", "React", "TypeScript", "MiniLM", "XGBoost", "Ranking"],
    link: "https://github.com/kenny1031/airbnb-retrieval-ranking-engine",
  },
  {
    title: "Geospatial Recommendation System for Site Selection",
    period: "2026",
    description:
      "Built an end-to-end recommendation system that ranks (area, industry) pairs for site selection using large-scale Foursquare Open Places data, PostgreSQL serving tables, geospatial feature engineering, and neural ranking models.",
    highlights: [
      "Processed 1.49M+ Australian records from a 108M-row source dataset",
      "Engineered competition, diversity, penetration, and neighbour-aware signals",
      "Benchmarked XGBoost, MLP, and a custom LocalConvRanker",
    ],
    stack: ["Python", "PostgreSQL", "PyTorch", "XGBoost", "Geospatial ML"],
    link: "https://devpost.com/software/districtlens",
  },
  {
    title: "Regime-Aware Dynamic Asset Allocation",
    period: "2026",
    description:
      "Designed a quantitative research pipeline for market regime detection and dynamic allocation using unsupervised learning, supervised models, sequence models, and walk-forward backtesting.",
    highlights: [
      "Implemented HMM, GMM, and KMeans regime detection",
      "Built XGBoost and LSTM regime classifiers",
      "Integrated regime-conditioned portfolio optimisation and evaluation",
    ],
    stack: ["Python", "PyTorch", "scikit-learn", "XGBoost", "Quant Research"],
    link: "https://github.com/kenny1031/regime-aware-dynamic-asset-allocation",
  },
  {
    title: "Helmet Detection System (YOLOv8)",
    period: "2025",
    description:
      "Developed an end-to-end computer vision pipeline for helmet detection, covering dataset preparation, training, evaluation, error analysis, and API-based inference.",
    highlights: [
      "Integrated FiftyOne for dataset curation and analysis",
      "Trained and evaluated YOLO-based detection models",
      "Exposed inference through a FastAPI service",
    ],
    stack: ["Python", "YOLOv8", "FiftyOne", "FastAPI", "Computer Vision"],
    link: "https://github.com/kenny1031/cv-helmet-detection-system",
  },
];

const skillGroups = [
  {
    title: "ML / AI",
    items: ["PyTorch", "scikit-learn", "XGBoost", "YOLO", "RAG", "Model Evaluation"],
  },
  {
    title: "Backend / Data",
    items: ["FastAPI", "PostgreSQL", "SQL", "Redis", "Docker", "REST APIs"],
  },
  {
    title: "Programming",
    items: ["Python", "Java", "C", "TypeScript", "Git", "Linux"],
  },
];

const fadeUp = {
  hidden: { opacity: 0, y: 24 },
  visible: { opacity: 1, y: 0 },
};

function Pill({ children }) {
  return (
    <span className="rounded-full border border-white/10 bg-white/5 px-3 py-1 text-sm text-neutral-200">
      {children}
    </span>
  );
}

function PrimaryButton({ href, children }) {
  return (
    <a
      href={href}
      className="inline-flex items-center justify-center rounded-2xl bg-white px-5 py-3 text-sm font-medium text-neutral-900 transition hover:scale-[1.02]"
    >
      {children}
    </a>
  );
}

function SecondaryButton({ href, children, external = false }) {
  return (
    <a
      href={href}
      target={external ? "_blank" : undefined}
      rel={external ? "noreferrer" : undefined}
      className="inline-flex items-center justify-center rounded-2xl border border-white/15 bg-transparent px-5 py-3 text-sm font-medium text-white transition hover:bg-white/10"
    >
      {children}
    </a>
  );
}

function SectionCard({ children, className = "" }) {
  return <div className={`rounded-[1.5rem] border border-white/10 bg-white/5 ${className}`}>{children}</div>;
}

function validatePortfolioData() {
  const hasProjects = Array.isArray(projects) && projects.length > 0;
  const validProjects = hasProjects && projects.every((project) => project.title && project.description && Array.isArray(project.stack));
  const hasSkillGroups = Array.isArray(skillGroups) && skillGroups.length > 0;

  if (!hasProjects) {
    throw new Error("projects must contain at least one project");
  }

  if (!validProjects) {
    throw new Error("each project must include title, description, and stack");
  }

  if (!hasSkillGroups) {
    throw new Error("skillGroups must contain at least one skill group");
  }

  return true;
}

validatePortfolioData();

export default function KennyPortfolioWebsite() {
  return (
    <div className="min-h-screen overflow-x-hidden bg-neutral-950 text-neutral-100">
      <div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_top_right,rgba(59,130,246,0.16),transparent_22%),radial-gradient(circle_at_top_left,rgba(168,85,247,0.12),transparent_20%),linear-gradient(to_bottom,rgba(255,255,255,0.02),rgba(255,255,255,0))]" />

      <header className="sticky top-0 z-30 border-b border-white/10 bg-neutral-950/80 backdrop-blur">
        <div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-4">
          <p className="text-sm font-medium uppercase tracking-[0.2em] text-neutral-400">Kenny Yu</p>
          <nav className="hidden gap-6 text-sm text-neutral-300 md:flex">
            <a href="#about" className="transition hover:text-white">About</a>
            <a href="#projects" className="transition hover:text-white">Projects</a>
            <a href="#skills" className="transition hover:text-white">Skills</a>
            <a href="#contact" className="transition hover:text-white">Contact</a>
          </nav>
        </div>
      </header>

      <main className="mx-auto flex max-w-6xl flex-col gap-20 px-6 py-12 md:py-20">
        <section className="grid items-center gap-10 md:grid-cols-[1.2fr_0.8fr]">
          <motion.div initial="hidden" animate="visible" variants={fadeUp} transition={{ duration: 0.5 }}>
            <div className="mb-5 inline-flex rounded-full border border-white/10 bg-white/5 px-4 py-1 text-sm text-neutral-200">
              ML Engineer / Retrieval / Ranking Systems
            </div>
            <h1 className="max-w-3xl text-4xl font-semibold leading-tight tracking-tight md:text-6xl">
              Building retrieval, ranking, and end-to-end ML systems for real products.
            </h1>
            <p className="mt-6 max-w-2xl text-base leading-8 text-neutral-300 md:text-lg">
              I’m Kenny, a Computer Science and Financial Mathematics student at the University of Sydney. I enjoy designing systems that connect data, models, and product-facing applications — especially in retrieval, ranking, recommendation, machine learning, and backend engineering.
            </p>

            <div className="mt-8 flex flex-wrap gap-3">
              <PrimaryButton href="#projects">View Projects</PrimaryButton>
              <SecondaryButton href="mailto:kunda031031@gmail.com">Contact Me</SecondaryButton>
            </div>

            <div className="mt-8 flex flex-wrap items-center gap-5 text-sm text-neutral-400">
              <div>Sydney, Australia</div>
              <div>University of Sydney</div>
            </div>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, scale: 0.96 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.55 }}
            className="rounded-[2rem] border border-white/10 bg-white/5 p-6 shadow-2xl shadow-black/20"
          >
            <div className="mb-6 flex justify-center">
              <img
                src="/portfolio_web_pfp.JPG"
                alt="Kenny Yu"
                className="h-65 w-60 rounded-3xl object-cover border border-white/10 shadow-xl"
              />
            </div>
            <div className="grid gap-4 sm:grid-cols-2">
              {[
                ["Focus", "Retrieval · Ranking · ML Systems"],
                ["Degree", "CS + Financial Maths"],
                ["Interests", "Search · Recommendation · Quant"],
                ["Tooling", "Python · Java · SQL · Docker"],
              ].map(([label, value]) => (
                <div key={label} className="rounded-2xl border border-white/10 bg-black/20 p-4">
                  <p className="text-xs uppercase tracking-[0.2em] text-neutral-500">{label}</p>
                  <p className="mt-2 text-sm font-medium text-neutral-100">{value}</p>
                </div>
              ))}
            </div>
            <div className="mt-6 rounded-2xl border border-white/10 bg-gradient-to-br from-blue-500/10 to-purple-500/10 p-5">
              <p className="text-sm text-neutral-300">
                Looking for software, ML engineering, and data-centric internship opportunities where I can contribute
                across modelling, backend systems, and product implementation.
              </p>
            </div>
          </motion.div>
        </section>

        <motion.section
          id="about"
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, amount: 0.2 }}
          variants={fadeUp}
          transition={{ duration: 0.45 }}
          className="grid gap-6 md:grid-cols-3"
        >
          <div className="md:col-span-1">
            <p className="text-sm uppercase tracking-[0.2em] text-neutral-500">About</p>
            <h2 className="mt-3 text-3xl font-semibold">What I work on</h2>
          </div>
          <SectionCard className="p-6 md:col-span-2">
            <p className="leading-8 text-neutral-300">
              My projects usually sit at the intersection of <span className="text-white">machine learning</span>, <span className="text-white">retrieval and ranking systems</span>, and <span className="text-white">backend engineering</span>.
              I like building things end to end: ingesting and structuring data, training or integrating models,
              exposing them through APIs, and packaging the system in a way that feels production-oriented.
            </p>
            <p className="mt-4 leading-8 text-neutral-300">
              Recently, I’ve been exploring search, recommendation, ranking systems, quantitative modelling, and applied computer vision. I care about both the model side and the engineering side, 
              system is designed, tested, deployed, and extended really matter to me.
            </p>
          </SectionCard>
        </motion.section>

        <section id="projects" className="space-y-6">
          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, amount: 0.2 }}
            variants={fadeUp}
            transition={{ duration: 0.45 }}
          >
            <p className="text-sm uppercase tracking-[0.2em] text-neutral-500">Selected Work</p>
            <h2 className="mt-3 text-3xl font-semibold">Featured Projects</h2>
          </motion.div>

          <div className="grid gap-6 md:grid-cols-2">
            {projects.map((project, index) => (
              <motion.div
                key={project.title}
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true, amount: 0.2 }}
                variants={fadeUp}
                transition={{ duration: 0.4, delay: index * 0.05 }}
              >
                <SectionCard className="h-full p-6 transition hover:-translate-y-1 hover:border-white/20 hover:bg-white/[0.07]">
                  <div className="flex items-start justify-between gap-4">
                    <div>
                      <h3 className="text-xl font-semibold text-white">{project.title}</h3>
                      <p className="mt-2 text-sm text-neutral-400">{project.period}</p>
                    </div>
                    {project.link !== "#" && (
                      <a
                        href={project.link}
                        target="_blank"
                        rel="noreferrer"
                        className="rounded-full border border-white/10 px-3 py-2 text-xs text-neutral-300 transition hover:bg-white/10 hover:text-white"
                      >
                        View
                      </a>
                    )}
                  </div>

                  <p className="mt-4 leading-7 text-neutral-300">{project.description}</p>

                  <div className="mt-5 space-y-3">
                    {project.highlights.map((item) => (
                      <div key={item} className="flex gap-3 text-sm text-neutral-300">
                        <span className="mt-1 h-1.5 w-1.5 shrink-0 rounded-full bg-neutral-500" />
                        <span>{item}</span>
                      </div>
                    ))}
                  </div>

                  <div className="mt-5 flex flex-wrap gap-2">
                    {project.stack.map((tech) => (
                      <Pill key={tech}>{tech}</Pill>
                    ))}
                  </div>
                </SectionCard>
              </motion.div>
            ))}
          </div>
        </section>

        <section id="skills" className="space-y-6">
          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, amount: 0.2 }}
            variants={fadeUp}
            transition={{ duration: 0.45 }}
          >
            <p className="text-sm uppercase tracking-[0.2em] text-neutral-500">Capabilities</p>
            <h2 className="mt-3 text-3xl font-semibold">Skills & Tools</h2>
          </motion.div>

          <div className="grid gap-6 md:grid-cols-3">
            {skillGroups.map((group, index) => (
              <motion.div
                key={group.title}
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true, amount: 0.2 }}
                variants={fadeUp}
                transition={{ duration: 0.4, delay: index * 0.06 }}
              >
                <SectionCard className="h-full p-6">
                  <div className="flex h-11 w-11 items-center justify-center rounded-2xl border border-white/10 bg-white/5 text-sm font-semibold text-neutral-200">
                    {group.title.slice(0, 2)}
                  </div>
                  <h3 className="pt-4 text-xl font-semibold text-white">{group.title}</h3>
                  <div className="mt-4 flex flex-wrap gap-2">
                    {group.items.map((item) => (
                      <Pill key={item}>{item}</Pill>
                    ))}
                  </div>
                </SectionCard>
              </motion.div>
            ))}
          </div>
        </section>

        <motion.section
          id="contact"
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, amount: 0.2 }}
          variants={fadeUp}
          transition={{ duration: 0.45 }}
        >
          <SectionCard className="rounded-[2rem] bg-gradient-to-br from-white/8 to-white/4 p-8">
            <div className="flex flex-col gap-6 md:flex-row md:items-center md:justify-between">
              <div>
                <p className="text-sm uppercase tracking-[0.2em] text-neutral-500">Contact</p>
                <h2 className="mt-3 text-3xl font-semibold">Let’s build something meaningful.</h2>
                <p className="mt-3 max-w-2xl leading-7 text-neutral-300">
                  I’m interested in internships and project opportunities across software engineering, machine learning engineering, retrieval and ranking, and applied AI systems.
                </p>
              </div>
              <div className="flex flex-wrap gap-3">
                <PrimaryButton href="mailto:kunda031031@gmail.com">Email</PrimaryButton>
                <SecondaryButton href="https://github.com/kenny1031" external>
                  GitHub
                </SecondaryButton>
                <SecondaryButton href="https://www.linkedin.com/in/kenny-y-10106a22a" external>
                  LinkedIn
                </SecondaryButton>
              </div>
            </div>
          </SectionCard>
        </motion.section>
      </main>
    </div>
  );
}
